# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Richard Kotze - Web technologist and Software Engineer
description: > # this means to ignore newlines until "baseurl:"
  I'm a software engineer and I will post about a range of tech stuff.
  Mostly things I learn. Mostly into JavaScript and Elixir but also everything else.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://rkotze.github.io" # the base hostname & protocol for your site
tobe_url: "http://www.richardkotze.com"
twitter_username: richardkotze
github_username:  rkotze
google_username:  109155264212733458222?rel=author
facebook_username:  webdesign.develop

# Build settings
markdown: kramdown

exclude: ["readme.md"]